sudo: required
dist: trusty
language: python
python:
  - "3.5"

addons:
  apt:
    packages:
      - firefox
      - mercurial

install:
  - bash ci/install.sh

script:
  - bash ci/test.sh

notifications:
  irc:
    channels: "irc.freenode.org#baroque-dev"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    use_notice: true
    on_success: always
    on_failure: always

  email:
    on_success: change
    on_failure: change
