sudo: required
dist: trusty
language: python
python:
  - "3.5"

addons:
  apt:
    packages:
      - mercurial
      - python-dev
      - libunwind8-dev

install:
  - pushd .
  - bash ci/install.sh
  - cd vmprof-server
  - python manage.py runserver -v 3 &
  - sleep 3
  - popd

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - py.test testvmprof -v -s

notifications:
  irc:
    channels: "irc.freenode.org#baroque-dev"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    use_notice: true
    on_success: always
    on_failure: always

  email:
    on_success: change
    on_failure: change
